### ISSUE TITLE
2024年还能用，只是为了致谢

### ISSUE THREAD

**Issue by Steven630** [guo-yong-zhi/MailPush#4]
没想到这个插件现在还能用。作者好像已经很久没来了，在此说声谢谢。

**Comment by guo-yong-zhi** [comment]
哈哈，这是python标准库和imap协议的稳定性

**Comment by Steven630** [comment]
大佬竟然回复了！万一以后更新的话，可否考虑下载失败重试的选项。这样用户不用手动去邮箱设为未读再重新下载

**Comment by guo-yong-zhi** [comment]
不需要手动设为未读，点下面的`Fetch latest mails`系列可以重复下载最新的邮件

**Comment by Steven630** [comment]
> 不需要手动设为未读，点下面的`Fetch latest mails`系列可以重复下载最新的邮件

明白啦，是只会下载刚才失败的吗？

**Comment by guo-yong-zhi** [comment]
不同的按钮，对应重下最近的1封、3封或5封

**Comment by Steven630** [comment]
谢谢。你写的插件都很好用，那个Kindle浏览器也很不错。

**Comment by guo-yong-zhi** [comment]
新版（v1.6）下载失败的邮件应该不会变成已读了，可以试试

**Comment by Steven630** [comment]
> 新版（v1.6）下载失败的邮件应该不会变成已读了，可以试试

好的，过两天看看大文件失败能不能重试。会出现几个附件，有的成功有的失败的情况吗？比如某一天有三封邮件，其中两封的附件都下载成功了，一封的下载失败。选择重新抓取也是只会下载那失败的一封吗？

**Comment by guo-yong-zhi** [comment]
预期是这样的。不以天为单位，以封为单位

**Comment by Steven630** [comment]
请问安卓上有类似的推送插件吗？能自动下载邮件附件的

**Comment by guo-yong-zhi** [comment]
需求有点定制有点小众，恐怕没有趁手的app。你装个QPython，本插件倒是也可以跑，但操作起来可能也不方便。除非QPython能折腾自动任务，这还可能是个办法。

**Comment by Steven630** [comment]
> 需求有点定制有点小众，恐怕没有趁手的app。你装个QPython，本插件倒是也可以跑，但操作起来可能也不方便。除非QPython能折腾自动任务，这还可能是个办法。

确实有点小众了。现在用Kindle，越狱装了Koreader，Kindle处理器还是不太行。以后可能换成安卓的阅读器，所以想着能有推送最方便。安卓手机上倒是装了Pydroid

**Comment by guo-yong-zhi** [comment]
`cd /你的安装目录/MailPush; python3 -u src/mailpush.py`
把你kindle里的MailPush文件夹复制到安卓设备里，在Pydroid（的命令行）里执行上面的命令应该就可以

**Comment by Steven630** [comment]
> `cd /你的安装目录/MailPush; python3 -u src/mailpush.py`
> 把你kindle里的MailPush文件夹复制到安卓设备里，在Pydroid（的命令行）里执行上面的命令应该就可以

好的，感谢

**Comment by Steven630** [comment]
又来请教了。今天有6封邮件，各有一个附件，一共6个。其中5封邮件的5个附件都比较小，几百K。还有一封邮件的附件大，9MB。第一次用自定义下载，提示operation failed，此外无任何提示（result.txt是空白的）。但实际上那五个较小的附件都已经下载成功，只有大的那个下载失败。遇到这样的情况，有什么办法只重新下载那一个失败的吗？（比如按照文件名，如果文件名重复就不再下载？）另外这种大文件有什么办法提高下载成功概率吗？谢谢

**Comment by guo-yong-zhi** [comment]
新版（v1.6）再点`Fetch unread emails`的时候应该就是只重新下载失败的邮件吧？（如果不是，欢迎反馈）
result.txt是空白的时候可以看log.txt
大文件暂时没有特别好的办法，国内的网络环境比较差（下版我试试把超时时间放宽些）。贴下载链接而不是附件要好一些。

**Comment by Steven630** [comment]
> 新版（v1.6）再点`Fetch unread emails`的时候应该就是只重新下载失败的邮件吧？（如果不是，欢迎反馈）
> result.txt是空白的时候可以看log.txt
> 大文件暂时没有特别好的办法，国内的网络环境比较差（下版我试试把超时时间放宽些）。贴下载链接而不是附件要好一些。

好的，谢谢！再观察观察。中秋快乐😆

**Comment by Steven630** [comment]
@guo-yong-zhi 今天突然提示登录不了：

```
========== 2024-09-19 12:33:22 ==========
Traceback (most recent call last):
  File "/mnt/us/extensions/MailPush-1.6/src/mailpush.py", line 22, in <module>
    files = fetch_files(**config)
  File "/mnt/us/extensions/MailPush-1.6/src/fetchfiles.py", line 120, in fetch_files
    for msg_data in fetch_mails(**kargs):
  File "/mnt/us/extensions/MailPush-1.6/src/fetchmails.py", line 21, in fetch_mails
    connection.login(user, password)
  File "/mnt/us/python3/lib/python3.9/imaplib.py", line 612, in login
    raise self.error(dat[-1])
imaplib.IMAP4.error: b'LOGIN failed.'
kill: can't kill pid 6797: No such process
```

用的是outlook，昨天还好好的。连续几次都是这个错误提示

**Comment by guo-yong-zhi** [comment]
https://www.mobileread.com/forums/showthread.php?t=363432 见10楼的评论。outlook邮箱收紧了登录条件，不能用了。换其他邮箱，比如qq邮箱试试吧。

**Comment by Steven630** [comment]
> https://www.mobileread.com/forums/showthread.php?t=363432 见10楼的评论。outlook邮箱收紧了登录条件，不能用了。换其他邮箱，比如qq邮箱试试吧。

好吧，那我还算多用了几天。通知说的是9.16就不能用了……Python没法实现高级的验证方式了对吗

**Comment by guo-yong-zhi** [comment]
微软私有的验证方法，不通用，不可能专门为他实现

**Comment by Steven630** [comment]
> 微软私有的验证方法，不通用，不可能专门为他实现

刚才换163邮箱，也不支持吗？

```
========== 2024-09-19 19:01:07 ==========
* 2024-09-19 19:01:08, login
Traceback (most recent call last):
  File "/mnt/us/extensions/MailPush-1.6/src/mailpush.py", line 22, in <module>
    files = fetch_files(**config)
  File "/mnt/us/extensions/MailPush-1.6/src/fetchfiles.py", line 120, in fetch_files
    for msg_data in fetch_mails(**kargs):
  File "/mnt/us/extensions/MailPush-1.6/src/fetchmails.py", line 24, in fetch_mails
    num_msgs = int(data[0])
ValueError: invalid literal for int() with base 10: b'SELECT Unsafe Login. Please contact kefu@188.com for help'
kill: can't kill pid 11356: No such process
```

**Comment by guo-yong-zhi** [comment]
![image](https://github.com/user-attachments/assets/0e35f874-3373-4696-bc66-64e433347878)
IMAP服务开启了吗？

imap.188.com 的 host 配置了吗？

188不清楚，163的授权码180天过期，比较麻烦。我现在用的QQ邮箱没问题。

**Comment by guo-yong-zhi** [comment]
https://help.mail.163.com/faqDetail.do?code=d7a5dc8471cd0c0e8b4b8f4f8e49998b374173cfe9171305fa1ce630d7f67ac2eda07326646e6eb0

搜了下，不是上面说的原因，而是163邮箱有奇怪的讲究

**Comment by Steven630** [comment]
> https://help.mail.163.com/faqDetail.do?code=d7a5dc8471cd0c0e8b4b8f4f8e49998b374173cfe9171305fa1ce630d7f67ac2eda07326646e6eb0
> 
> 搜了下，不是上面说的原因，而是163邮箱有奇怪的讲究

163邮箱设置应该没问题，180天的授权码确实麻烦，我是开启了之后才知道的。QQ邮箱刚注册，还得等两个礼拜。看来没办法了，只能先等等

**Comment by guo-yong-zhi** [comment]
最新代码已经支持163了。我测试没有问题。你可以自己Download ZIP，或者等我发布1.7版本
![image](https://github.com/user-attachments/assets/a3cc49a9-6fc4-4ba6-a0e9-764633940970)

**Comment by Steven630** [comment]
这下可以了，谢谢大佬。
